### ISSUE TITLE
貌似失效了

### ISSUE THREAD

**Issue by ginitaimeiyty** [mcitem/WELearnTestAIHelper#1]
等待好几分钟黑框里也没有任何内容，剪切板里面也没有
![屏幕截图 2024-05-21 185445](https://github.com/mcitem/WELearnTestAIHelper/assets/104124470/ccd8473c-45ee-4fbe-964e-88b5d7f19813)

**Comment by mcitem** [comment]
你可以先看下控制台具体的报错是什么，

第一是有可能是页面还没加载出来脚本就先运行了，(毕竟是脚本里是写死的硬等待，懒得监听页面加载

如果不是脚本执行顺序的问题，获取不到我也没办法帮你测试，除非你能给我提供账号(

你可以发送邮箱↓
mcitem@qq.com
